#' Random dataset generated by the gateveys package
#'
#' This is a simple random sample panel dataset which was created with the help
#' of several functions of this package. It's just a convenience dataset used 
#' in some of the examples, that data has not to be recreated everytime. 
#'
#' @name randomPanel
#' @docType data
#' @author Matthias Bannert \email{bannert@@kof.ethz.ch}
#' @keywords data
NULL